site_name: SA-AwsAssets
edit_uri: edit/main/docs/
repo_url: https://github.com/ZachChristensen28/SA-AwsAssets
repo_name: ZachChristensen28/SA-AwsAssets
site_description: >-
  Welcome to the Home of the SA-AwsAssets Add-on for Splunk Enterprise Security documentation. This supporting add-on comes with prebuilt content for AWS asset data to be easily used with Splunk Enterprise Security's asset database.

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/sa-aws-logo.svg
  favicon: assets/sa-aws-logo.svg
  features:
    # - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zachthesplunker/
    - icon: fontawesome/brands/github
      link: https://github.com/ZachChristensen28
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ZachTheSplunker
    - icon: simple/ghost
      link: https://zachthesplunker.com

# extra_css:
#   - stylesheets/extra.css

copyright: Copyright &copy; 2023 ZachTheSplunker

nav:
  - Home: index.md
  - Quick Start:
      - Prerequisites: quickstart/prerequisites.md
      - Install: quickstart/install.md
      - Quickstart: quickstart/quickstart.md
  - Configure:
      - configure/index.md
      - Update Priority: configure/priority.md
      - Update Category: configure/category.md
      - Update Schedule: configure/schedule.md
      - Update Cleanup: configure/cleanup.md
      - Best Practice:
          - Clone Saved Search: configure/best-practice/clone-search.md
  - Reference:
      - All Configurations: reference/all-configurations.md
      - Asset Database mapping: reference/asset-mapping.md
      - Example Output: reference/example.md
      - Field reference:
          - Category: reference/category.md
  - Troubleshooting:
      - troubleshooting/index.md
      - Solutions Guide:
          - Asset Merge: troubleshooting/solution-guides/asset-merge.md
  - Release Notes:
      - Release Notes: releases/index.md
      - Release History: releases/release-history.md
