name: Splunk Appinspect
on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - "src/**"
    types: [opened, ready_for_review]

jobs:
  call-packaging-workflow:
    uses: ZachChristensen28/splunk-github-wfa/.github/workflows/appinspect.yml@61f404792eba6f8c22465b8a6c96034ee20f2518
    secrets:
      API_USER: ${{ secrets.API_USER }}
      API_PASS: ${{ secrets.API_PASS }}
