name: Splunk Appinspect
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    paths:
      - "SA-AwsAssets/**"
    types: [opened, ready_for_review]

jobs:
  call-packaging-workflow:
    uses: ZachTheSplunker/splunk-github-wfa/.github/workflows/appinspect.yml@main
          
